image: php:8.2

services:
  - mysql:8.0

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: dusk_test
  DB_HOST: mysql
  DB_PORT: 3306
  DB_DATABASE: dusk_test
  DB_USERNAME: root
  DB_PASSWORD: root
  APP_ENV: testing
  BROWSER: chrome

stages:
  - test


dusk_test:
  stage: test
  script:
    - php artisan dusk
