image: php:8.2

services:
  - mysql:8.0

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: dusk_test
  DB_HOST: mysql
  DB_PORT: 3306
  DB_DATABASE: dusk_test
  DB_USERNAME: root
  DB_PASSWORD: root
  APP_ENV: testing
  BROWSER: chrome

stages:
  - test

before_script:
  - apt-get update
  - apt-get install -y unzip zip git curl libzip-dev libpng-dev libonig-dev libxml2-dev libsqlite3-dev sqlite3 chromium chromium-driver
  - docker-php-ext-install pdo pdo_mysql zip
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install
  - cp .env.dusk.local .env
  - php artisan key:generate
  - php artisan migrate --force
  - php artisan dusk:chrome-driver
  - php artisan serve --host=127.0.0.1 --port=8000 &
  - sleep 10

dusk_test:
  stage: test
  script:
    - php artisan dusk
