name: Laravel Dusk Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dusk-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Install Chrome and ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 'latest'

      - name: Start Laravel Server
        run: php artisan serve --host=127.0.0.1 --port=8000 &
      
      - name: Wait for Laravel to be ready
        run: sleep 10

      - name: Run Laravel Dusk Tests
        env:
          APP_URL: http://127.0.0.1:8000
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan dusk
